/*
 * File: app/view/Actions.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Actions', {
    extend: 'Ext.grid.Panel',

    height: 250,
    width: 400,
    closable: true,
    title: '功能区',
    columnLines: false,
    disableSelection: true,
    enableColumnHide: false,
    enableColumnMove: false,
    enableColumnResize: false,
    forceFit: true,
    sortableColumns: false,
    store: 'Actions',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'description',
                    text: '操作按钮'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'actionUrl',
                    text: ''
                }
            ],
            listeners: {
                cellclick: {
                    fn: me.onGridpanelCellClick,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var tmp = Ext.create(record.data.actionUrl);
        Ext.getCmp('idMain').add(tmp);
        Ext.getCmp('idMain').setActiveTab(tmp);
        //存在bug。在加入tmp后，应该将tab的激活页面转至tmp。
    }

});