/*
 * File: app/view/Index.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Index', {
    extend: 'Ext.container.Container',

    height: 600,
    id: 'idViewport',
    width: 1320,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'center',
                    id: 'idLogin',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    title: '中国传媒大学毕业设计平台',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            id: 'idUserName',
                            fieldLabel: '用户号码'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            id: 'idPassword',
                            fieldLabel: '密码',
                            inputType: 'password'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            text: '登录',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'south',
                    height: 150
                },
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'west',
                    width: 150
                },
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'east',
                    width: 150
                },
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'north',
                    height: 150
                }
            ],
            listeners: {
                beforerender: {
                    fn: me.onIdViewportBeforeRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var form = Ext.getCmp('idLogin');
        //var password = form.findField('password').getValue();
        //var encrypt = hex_md5(password);

        var encrypt = "e10adc3949ba59abbe56e057f20f883e";        
        //form.findField('password').setValue(encrypt);
        if (form.isValid()) {
            Ext.Ajax.request({
                url : 'rest/auth/login',
                headers : {
                    "Accept" : "application/json"
                },
                method : 'POST',
                params : {
                    'userName' : Ext.getCmp('idUserName').getValue(),
                    'password' : encrypt
                },
                success : function(response, opts) {
                    var t = JSON.parse(response.responseText);
                    if (t.status === "-1") {
                        Ext.Msg.alert("登录失败！" + t.msg);
                        return;
                    } else if (t.status === "0") {
                        viewport = Ext.getCmp('idViewport');
                        viewport.removeAll();
                        loader = Ext.create('Cucgp.view.Loader');
                        viewport.insert(loader);
                        return;
                    }
                },
                failure : function(response, opts) {
                    var t = JSON.parse(response.responseText);
                    Ext.Msg.alert("登录失败！ErrorMsg:" + t.msg);
                    return;
                }
            });
        }
        return;

    },

    onIdViewportBeforeRender: function(component, eOpts) {
        Ext.Ajax.defaultHeaders = {
            'Accept' : 'application/json'
        };
    }

});