/*
 * File: app/view/Loader.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Loader', {
    extend: 'Ext.container.Container',

    height: 600,
    width: 1320,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                afterrender: {
                    fn: me.onContainerAfterRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onContainerAfterRender: function(component, eOpts) {
        var actions = Ext.create('Cucgp.view.Actions', {region : 'west', flex: 1});
        var main = Ext.create('Cucgp.view.Main', {region : 'center', flex : 5});
        this.add(actions);
        this.add(main);
        actions.getStore().reload();
    }

});