/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    height: 387,
    width: 668,
    layout: {
        type: 'anchor'
    },
    title: '流程管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'slider',
                    anchor: '100%',
                    fieldLabel: '流程控制',
                    value: 1,
                    maxValue: 5
                }
            ],
            dockedItems: [
                {
                    xtype: 'progressbar',
                    anchor: '100%',
                    dock: 'top',
                    value: 0.2
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom'
                }
            ]
        });

        me.callParent(arguments);
    }

});