/*
 * File: app/view/Tca.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Tca', {
    extend: 'Ext.form.Panel',

    height: 371,
    width: 636,
    bodyPadding: 10,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: '项目名称'
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: '项目人数'
                },
                {
                    xtype: 'htmleditor',
                    anchor: '100%',
                    height: 150,
                    fieldLabel: ''
                }
            ]
        });

        me.callParent(arguments);
    }

});