/*
 * File: app/view/Tcas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Tcas', {
    extend: 'Ext.grid.Panel',

    height: 265,
    id: 'idTcas',
    width: 671,
    closable: true,
    title: '审核教师申报',
    store: 'Tcas',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tbar: [
                {
                    text: '通过',
                    handler: function() {
                                     var s = this.up('grid').getSelectionModel().getSelection()[0];
                                     var record = this.up('grid').getStore().getAt(s.index);
                                     record.set("status", 1);
                                     record.commit();
                                     this.up('grid').getStore().commitChanges();
                                     this.up('grid').plugins[0].cancelEdit();   
                                    }
                },
                {
                    text: '不通过',
                    handler: function() {
                                     var s = this.up('grid').getSelectionModel().getSelection()[0];
                                     var record = this.up('grid').getStore().getAt(s.index);
                                     record.set("status", 2);
                                     record.commit();
                                     this.up('grid').getStore().commitChanges();
                                     this.up('grid').plugins[0].cancelEdit();
                                    }
                },
                {
                    text: '查看介绍',
                    handler: function() {
                                     var s = this.up('grid').getSelectionModel().getSelection()[0];
                                     var record = this.up('grid').getStore().getAt(s.index);
                                     var introduction = record.get("introduction");
                                        Ext.create('Ext.window.Window', {
                                                    title: '申报介绍',
                                                    height: 200,
                                                    width: 400,
                                                    autoScroll: true,
                                                    html: introduction
                                        }).show();      
                                    }
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tcaId',
                    text: 'id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'tcaName',
                    text: '申报名称'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'numerator',
                    text: '毕设人数'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userName',
                    text: '教师姓名'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                    },
                    hidden: true,
                    dataIndex: 'introduction',
                    text: '介绍'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == 0) {
                            return "待领导审核";
                        }

                        if (value == 1) {
                            return "审核通过";
                        }

                        if (value == 2) {
                            return "审核不通过";
                        }
                        if (value > 2) {
                            return "开发中";
                        }
                    },
                    dataIndex: 'status',
                    text: '课程状态'
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {

                })
            ]
        });

        me.callParent(arguments);
    }

});