/*
 * File: app/view/Users.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Users', {
    extend: 'Ext.grid.Panel',

    height: 427,
    id: 'idUsers',
    width: 716,
    title: '账户管理',
    forceFit: false,
    store: 'Users',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userId',
                    text: '用户ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userName',
                    text: '账户',
                    editor: {
                        xtype: 'textareafield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'password',
                    text: '密码',
                    editor: {
                        xtype: 'textareafield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'groupId',
                    text: '分组'
                }
            ],
            viewConfig: {
                plugins: [
                    Ext.create('Ext.grid.plugin.DragDrop', {

                    })
                ]
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'Users'
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {
                    pluginId: 'usersEdit',
                    listeners: {
                        canceledit: {
                            fn: me.onRowEditingCanceledit,
                            scope: me
                        },
                        edit: {
                            fn: me.onRowEditingEdit,
                            scope: me
                        },
                        beforeedit: {
                            fn: me.onRowEditingBeforeEdit,
                            scope: me
                        }
                    }
                })
            ],
            selModel: Ext.create('Ext.selection.RowModel', {

            })
        });

        me.callParent(arguments);
    },

    onRowEditingCanceledit: function(editor, context, eOpts) {
        Ext.MessageBox.confirm('取消编辑','确认取消变更么？',
        function (button) {
            if(button == 'yes') {
                console.debug('已取消');
            } else {
                console.debug('未取消');
            }
        }
        );
    },

    onRowEditingEdit: function(editor, context, eOpts) {
        Ext.MessageBox.confirm('更改','确认变更么？',
        function (button) {
            if(button == 'yes') {
                console.debug('已取消');
            } else {
                console.debug('未取消');
            }
        }
        );
    },

    onRowEditingBeforeEdit: function(editor, context, eOpts) {

        Ext.getCmp('idUsers').getPlugin('usersEdit').startEdit(0,0);
    }

});