/*
 * File: app/view/Workflows.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.view.Workflows', {
    extend: 'Ext.grid.Panel',

    height: 250,
    id: 'idWorkflows',
    width: 400,
    title: 'My Grid Panel',
    store: 'Workflows',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            tbar: [
                {
                    text: '教师申报',
                    handler: function() {
                
                                            }
                },
                {
                    text: '审核发布',
                    handler: function() {
                
                                            }
                },
                {
                    text: '学生执行',
                    handler: function() {
                
                                    }
                },
                {
                    text: '总评分数',
                    handler: function() {
                
                                    }
                },
                {
                    text: '关闭流程',
                    handler: function() {
                
                                    }
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'workflowName',
                    text: '流程名'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'workflowStatus',
                    text: '流程状态'
                },
                {
                    xtype: 'gridcolumn',
                    text: '状态说明'
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {

                })
            ]
        });

        me.callParent(arguments);
    }

});