/*
 * File: app/model/Student.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.model.Student', {
    extend: 'Ext.data.Model',

    idProperty: 'userId',

    fields: [
        {
            name: 'studentName'
        },
        {
            name: 'telephone'
        },
        {
            name: 'email'
        },
        {
            name: 'weibo'
        },
        {
            name: 'introduction'
        },
        {
            name: 'classroomName'
        },
        {
            name: 'departmentName'
        },
        {
            name: 'userId',
            type: 'int'
        },
        {
            name: 'userHome',
            type: 'string'
        },
        {
            name: 'password',
            type: 'string'
        },
        {
            name: 'userName',
            type: 'string'
        },
        {
            name: 'groupId',
            type: 'int'
        }
    ]
});