/*
 * File: app/model/Tca.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.model.Tca', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'tcaId',
            type: 'int'
        },
        {
            name: 'tcaName',
            type: 'string'
        },
        {
            name: 'userName',
            type: 'string'
        },
        {
            name: 'introduction',
            type: 'string'
        },
        {
            name: 'numerator',
            type: 'string'
        },
        {
            name: 'status',
            type: 'int'
        }
    ]
});