/*
 * File: app/store/Stuas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.store.Stuas', {
    extend: 'Ext.data.Store',

    requires: [
        'Cucgp.model.Stua'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Cucgp.model.Stua',
            storeId: 'MyStore5',
            proxy: {
                type: 'ajax',
                api: {
                    create: 'rest/stuas/creates',
                    read: 'rest/stuas/reads',
                    update: 'rest/stuas/updates',
                    destroy: 'rest/stuas/deletes'
                },
                reader: {
                    type: 'json',
                    root: 'stuas'
                }
            }
        }, cfg)]);
    }
});