/*
 * File: app/store/Workflows.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cucgp.store.Workflows', {
    extend: 'Ext.data.Store',

    requires: [
        'Cucgp.model.Workflow'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'Cucgp.model.Workflow',
            storeId: 'MyStore3',
            proxy: {
                type: 'ajax',
                api: {
                    create: 'rest/workflows/creates',
                    read: 'rest/workflows/reads',
                    update: 'rest/workflows/updates',
                    destroy: 'rest/workflows/deletes'
                },
                reader: {
                    type: 'json',
                    root: 'workflows'
                }
            }
        }, cfg)]);
    }
});